#### Lecture 1 Notes

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Phone data as per lecture materials.
# x = screen time in minutes
# y = percent battery used
phones = {
    "x":[568,341,609,477,511],
    "y":[75,46,87,59,61]
}

df = pd.DataFrame(phones)
df

     x   y
0  568  75
1  341  46
2  609  87
3  477  59
4  511  61

In [3]:
# First, let's retrieve the means of the x and y columns.
x_mean = df['x'].mean()
y_mean = df['y'].mean()

# This point will always pass through the regression line.
print(x_mean, y_mean)

501.2 65.6

In [4]:
# Lets find the distances of each point from the means
df['x_diff'] = df['x'] - x_mean
df['y_diff'] = df['y'] - y_mean
df.head(3)

     x   y  x_diff  y_diff
0  568  75    66.8     9.4
1  341  46  -160.2   -19.6
2  609  87   107.8    21.4

In [5]:
df['x_diff * y_diff'] = df['x_diff'] * df['y_diff']
df["x_diff^2"] = df["x_diff"] ** 2
df.head(2)

     x   y  x_diff  y_diff  x_diff * y_diff  x_diff^2
0  568  75    66.8     9.4           627.92   4462.24
1  341  46  -160.2   -19.6          3139.92  25664.04

In [7]:
numerator = df['x_diff * y_diff'].sum()
denomenator = df['x_diff^2'].sum()

m = numerator / denomenator
print(m)

0.1458773286069839

In [11]:
b = y_mean - m * x_mean
print(b.round(2))

-7.51

In [15]:
line_regression = f"y = {m.round(2)}x + {b.round(2)}"
line_regression

'y = 0.15x + -7.51'

In [17]:
sns.regplot(df,"x","y")

TypeError: regplot() takes from 0 to 1 positional arguments but 3 were given